### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [efekocatas/prj-rev-bwfs-dasmoto#8]
It is always a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are several shared properties for several of your selectors, which you can simplify by applying to multiple selectors art once, rather than individually. For instance,

```css
h1, h2, .price, p {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  color: white;
  font-weight: 32px;
}
```
